CREATE TABLE productos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    tipo VARCHAR(50),
    marca VARCHAR(50),
    descripcion TEXT,
    precio DECIMAL(10,2),
    stock INT,
    imagen VARCHAR(255)
);

INSERT INTO productos (nombre, tipo, marca, descripcion, precio, stock, imagen) VALUES
('Motosierra Stihl MS 180', 'motosierra', 'Stihl', 'Motosierra ligera para trabajos forestales básicos', 299.99, 12, 'motosierra_stihl_ms180.jpg'),
('Motosierra Stihl MS 250', 'motosierra', 'Stihl', 'Motosierra media para tala y poda', 419.50, 8, 'motosierra_stihl_ms250.jpg'),
('Motosierra Husqvarna 135', 'motosierra', 'Husqvarna', 'Motosierra potente para uso semiprofesional', 459.00, 6, 'motosierra_husqvarna_135.jpg'),
('Motosierra Husqvarna 445 II', 'motosierra', 'Husqvarna', 'Motosierra pro para tala intensiva', 649.00, 4, 'motosierra_husqvarna_445II.jpg'),
('Desbrozadora Husqvarna 525R', 'desbrozadora', 'Husqvarna', 'Desbrozadora profesional con motor X-Torq', 349.50, 8, 'desbrozadora_husqvarna_525r.jpg'),
('Desbrozadora Echo SRM-2620T', 'desbrozadora', 'Echo', 'Desbrozadora ligera a gasolina para limpieza de maleza', 289.99, 10, 'desbrozadora_echo_srm2620t.jpg'),
('Desbrozadora Echo SRM-4605U', 'desbrozadora', 'Echo', 'Desbrozadora profesional para grandes superficies', 539.00, 5, 'desbrozadora_echo_srm4605u.jpg'),
('Sopladora Husqvarna 325iB', 'sopladora', 'Husqvarna', 'Sopladora a batería para limpieza de restos forestales', 229.00, 15, 'sopladora_husqvarna_325iB.jpg'),
('Sopladora Echo ES-250ES', 'sopladora', 'Echo', 'Sopladora ligera para mantenimiento de senderos y caminos', 179.99, 20, 'sopladora_echo_es250es.jpg'),
('Taladro Bosch GSR 18-2-Li', 'taladro', 'Bosch', 'Taladro percutor sin cable, ideal para montaje de estructuras de madera', 129.99, 18, 'taladro_bosch_gsr18-2li.jpg'),
('Taladro Makita HP1630', 'taladro', 'Makita', 'Taladro percutor eléctrico para perforaciones en obra forestal', 99.90, 22, 'taladro_makita_hp1630.jpg'),
('Taladro Milwaukee M18 FDD2', 'taladro', 'Milwaukee', 'Taladro profesional sin cable para obra exigente', 249.00, 9, 'taladro_milwaukee_m18fdd2.jpg'),
('Hacha Fiskars X27', 'hacha', 'Fiskars', 'Hacha de tala clásica para uso forestal', 79.90, 30, 'hacha_fiskars_x27.jpg'),
('Hacha Husqvarna Small Forest Axe', 'hacha', 'Husqvarna', 'Hacha ligera para trabajos de limpieza y tala menor', 59.00, 25, 'hacha_husqvarna_small_forest_axe.jpg'),
('Maza Estwing Fibre Handle Sledge 16lb', 'maza', 'Estwing', 'Maza de peso para golpes fuertes en labores de derribo', 119.00, 12, 'maza_estwing_sledge16lb.jpg'),
('Maza Bahco S817-16', 'maza', 'Bahco', 'Maza profesional 16 lb para uso forestal intensivo', 139.00, 7, 'maza_bahco_s817-16.jpg'),
('Aceite 2T Motul 800 0.6L', 'accesorio', 'Motul', 'Aceite sintético para mezcla de motores 2 tiempos de maquinaria forestal', 8.99, 40, 'aceite_motul_800_0.6l.jpg'),
('Aceite Husqvarna Pro 2 T 1L', 'accesorio', 'Husqvarna', 'Aceite para motosierra y desbrozadora 2 tiempos', 14.50, 35, 'aceite_husqvarna_pro2t_1l.jpg'),
('Hilo Desbrozadora Oregon S93-50-80-R', 'accesorio', 'Oregon', 'Hilo semi-automático para desbrozadoras', 12.90, 50, 'hilo_oregon_s93-50-80r.jpg'),
('Hilo Desbrozadora Echo E-Chop 25-2-20', 'accesorio', 'Echo', 'Hilo de alta resistencia para desbrozadoras metálicas', 15.99, 45, 'hilo_echo_echop_25-2-20.jpg'),
('Guantes Forestales Pinewood 6346', 'accesorio', 'Pinewood', 'Guantes de protección para trabajos forestales', 19.90, 60, 'guantes_pinewood_6346.jpg'),
('Casco Forestal Stihl-Advance X-Vent', 'accesorio', 'Stihl', 'Casco con visera y protección auditiva para tala', 89.99, 20, 'casco_stihl_advance_x_vent.jpg'),
('Protector Auditivo 3M Peltor X5', 'accesorio', '3M', 'Protector auditivo profesional para tala y desbroce', 34.50, 25, 'protector_auditivo_3m_peltor_x5.jpg'),
('Motosierra EGO CS1800 40V', 'motosierra', 'EGO', 'Motosierra inalámbrica para trabajos forestales ligeros', 399.00, 14, 'motosierra_ego_cs1800_40v.jpg'),
('Desbrozadora EGO ST1531-L', 'desbrozadora', 'EGO', 'Desbrozadora inalámbrica profesional', 429.00, 6, 'desbrozadora_ego_st1531-l.jpg'),
('Sopladora Stihl BGA 57', 'sopladora', 'Stihl', 'Sopladora ligera a batería para limpieza de bosques y zonas recreativas', 149.00, 17, 'sopladora_stihl_bga57.jpg'),
('Taladro DeWalt DCD796D2-GB', 'taladro', 'DeWalt', 'Taladro sin cable profesional 18 V', 219.00, 11, 'taladro_dewalt_dcd796d2gb.jpg'),
('Hacha Husqvarna X-Cut X162', 'hacha', 'Husqvarna', 'Hacha profesional de talá-intermedia', 69.00, 28, 'hacha_husqvarna_xcut_x162.jpg'),
('Maza Stanley FatMax FME-MFM18XB-1', 'maza', 'Stanley', 'Maza profesional para uso forestal con mango de fibra', 79.90, 20, 'maza_stanley_fatmax_fmemfm18xb1.jpg'),
('Casco Forestal Husqvarna Technical XR', 'accesorio', 'Husqvarna', 'Casco técnico con protección para tala intensiva', 99.90, 15, 'casco_husqvarna_technical_xr.jpg'),
('Kit Limpieza Motosierra Stihl Premium', 'accesorio', 'Stihl', 'Kit de limpieza y mantenimiento para motosierra', 39.00, 30, 'kit_limpieza_motosierra_stihl_premium.jpg');

